### PR TITLE
Done with refactoring

### PR DESCRIPTION
**Pull request by samuelmaina**

### CODE REVIEW

**Comment by samuelmaina** [comment]
HI @GemmaTuron ,
Refactored and run the test for single and eml dataset. 
[eos3xip_cli_fetch.log](https://github.com/ersilia-os/eos3xip/files/12113874/eos3xip_cli_fetch.log)
[eos3xip_cli_predict.csv](https://github.com/ersilia-os/eos3xip/files/12113875/eos3xip_cli_predict.csv)

**Comment by GemmaTuron** [comment]
Update: we will re run the workflows to merge the PR once this is solved https://github.com/ersilia-os/ersilia/issues/753

**Comment by samuelmaina** [comment]
Hi @GemmaTuron ,
The PR has failed due to the python3.11 workflows, let me update them and make a new PR

**Comment by GemmaTuron** [comment]
Hi @samuelmaina 
It is fine, I merged the PR and updated the workflows on the main repo, which are now passing all. I've assigned model testing already!

**Pull request merged**
